@echo off
echo Deleting node_modules...
rmdir /s /q node_modules
echo Deleting package-lock.json...
del package-lock.json
echo Running npm install...
npm install
echo Deleting config files...
del postcss.config.js tailwind.config.js
echo Done!
